version: '3.8'
services:

  my-fe-app-service:
    container_name: voicefe-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://placeholder-api.com
    ports:
      - "3000:80"