version: '3.8'
# Trong file docker-compose.yml
services:
  # ... my-java-app-service, mongodb...

  my-fe-app-service:
    container_name: voicebe-frontend
    build:
      context: .  # ĐÃ SỬA: Trỏ đến thư mục gốc
      dockerfile: Dockerfile # File Dockerfile này cũng phải ở thư mục gốc
      args:
        VITE_API_URL: http://my-java-app-service:8080 
    ports:
      - "3000:80"
    depends_on:
      - my-java-app-service